---
title: Cool People
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: umitmertcakmak@gmail.com
description: Be nice.
baseurl: 
url: 
twitter_username: DataScienceJrny
github_username: Umit-Mert
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
